# Default values for ng-manager
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  kubeVersion: ""
  commonAnnotations: {}
  commonLabels: {}
  cg:
    enabled: false
  secrets:
    app:
      external:
        ## if FALSE, Generate all secrets within K8s Namespace
        ## If TRUE, use one of the followings kids to inject
        enabled: false
        kind:
          # use ExternalSecrets Operator
          externalSecrets: false
          # Use CSI Driver volume mount
          csiSecretDriver: false
    database:
      external:
        enabled: false
        kind:
          externalSecrets: false
          csiSecretDriver: false
  useExternalSecrets: false
  loadbalancerURL: ""
  monitoring:
    enabled: false
    managedPlatform: ""
    port: 8889
    path: /metrics
  database:
    postgres:
      ## - installed = true if installed within cluster
      installed: true
      ## - protocol to use for connection
      protocol: postgres
      ## - host array for external
      hosts:
        - postgres:5432
      ## - secret name containing external values
      secretName: ""
      ## - key within secret containing username
      userKey: ""
      ## - key within secret containing password
      passwordKey: ""
      ## - extra arguments set to connection string
      extraArgs: ""
    mongo:
      installed: true
      protocol: mongodb
      # --  provide default values if mongo.installed is set to false
      hosts: []
      secretName: ""
      userKey: ""
      passwordKey: ""
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              MONGO_USER: ""
              MONGO_PASSWORD: ""
        secretManagement:
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                MONGO_USER:
                  name: ""
                  property: ""
                MONGO_PASSWORD:
                  name: ""
                  property: ""
    timescaledb:
      installed: true
      protocol: "jdbc:postgresql"
      # --  provide default values if mongo.installed is set to false
      hosts:
        - timescaledb-single-chart:5432
      # -- Enable TimescaleDB SSL
      sslEnabled: false
      # -- TimescaleDB secrets
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              TIMESCALEDB_USERNAME: ""
              TIMESCALEDB_PASSWORD: ""
              TIMESCALEDB_SSL_ROOT_CERT: ""
        secretManagement:
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                TIMESCALEDB_USERNAME:
                  name: ""
                  property: ""
                TIMESCALEDB_PASSWORD:
                  name: ""
                  property: ""
                TIMESCALEDB_SSL_ROOT_CERT:
                  name: ""
                  property: ""
      secretName: ""
      userKey: ""
      passwordKey: ""
      extraArgs: ""
      certName: ""
      certKey: ""
    redis:
      installed: true
      protocol: "redis"
      # --  provide default values if redis.installed is set to false
      hosts:
        - redis:6379
      secretName: "redis-secret"
      ssl:
        enabled: false
        secret: ""
        caFileKey: ""
        trustStoreKey: ""
        trustStorePasswordKey: ""
      userKey: "redis-user"
      passwordKey: "redis-password"
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              REDIS_USERNAME: ""
              REDIS_PASSWORD: ""
        secretManagement:
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                REDIS_USERNAME:
                  name: ""
                  property: ""
                REDIS_PASSWORD:
                  name: ""
                  property: ""
  license:
    cg: ''
    ng: ''
    secrets:
      kubernetesSecrets:
        - secretName: ""
          keys:
            NG_LICENSE: ""
      secretManagement:
        externalSecretsOperator:
          - secretStore:
              name: ""
              kind: ""
            remoteKeys:
              NG_LICENSE:
                name: ""
                property: ""
  ccm:
    enabled: false
  opa:
    enabled: false
  chaos:
    enabled: false
  stackDriverLoggingEnabled: false
  smtpCreateSecret:
    enabled: false
    SMTP_PASSWORD: ""
    SMTP_HOST: ""
    SMTP_USERNAME: ""
    SMTP_USE_SSL: "true"
    SMTP_PORT: "465"
    secrets:
      kubernetesSecrets:
        - secretName: ""
          keys:
            SMTP_USERNAME: ""
            SMTP_PASSWORD: ""
            SMTP_HOST: ""
            SMTP_PORT: ""
            SMTP_USE_SSL: ""
      secretManagement:
        externalSecretsOperator:
          - secretStore:
              name: ""
              kind: ""
            remoteKeys:
              SMTP_USERNAME:
                name: ""
                property: ""
              SMTP_PASSWORD:
                name: ""
                property: ""
              SMTP_HOST:
                name: ""
                property: ""
              SMTP_PORT:
                name: ""
                property: ""
              SMTP_USE_SSL:
                name: ""
                property: ""
  ingress:
    # -- create ingress objects
    enabled: false
    # -- set ingress object classname
    className: harness
    # -- set host of ingressObjects
    hosts:
      - my-host.example.org
    # -- set tls for ingress objects
    tls:
      enabled: true
      secretName: ''
    # -- add annotations to ingress objects
    objects:
      annotations: {}
  istio:
    # -- create virtualServices objects
    enabled: false
    # -- create gateway and use in virtualservice
    gateway:
      create: false
    # -- if gateway not created, use specified gateway and host
    virtualService:
      gateways:
      hosts:
  proxy:
    enabled: false
    host: localhost
    port: 80
    username: ""
    password: ""
    protocol: http
  awsServiceEndpointUrls:
    enabled: false
    endPointRegion: us-east-2
    stsEndPointUrl: https://sts.us-east-2.amazonaws.com
    ecsEndPointUrl: https://ecs.us-east-2.amazonaws.com
    cloudwatchEndPointUrl: https://monitoring.us-east-2.amazonaws.com
  waitForInitContainer:
    enabled: true
    image:
      registry: docker.io
      repository: harness/helm-init-container
      pullPolicy: Always
      tag: "latest"
      digest: ""
      imagePullSecrets: []
redis:
  protocol: ""
  hosts: []
  secretName: ""
  userKey: ""
  passwordKey: ""
  extraArgs: ""
  secrets:
    kubernetesSecrets:
      - secretName: ""
        keys:
          REDIS_USERNAME: ""
          REDIS_PASSWORD: ""
    secretManagement:
      externalSecretsOperator:
        - secretStore:
            name: ""
            kind: ""
          remoteKeys:
            REDIS_USERNAME:
              name: ""
              property: ""
            REDIS_PASSWORD:
              name: ""
              property: ""
timescaledb:
  # -- TimescaleDB host names
  hosts: []
  # -- Enable TimescaleDB SSL
  # sslEnabled: false
  # -- TimescaleDB secrets
  secrets:
    kubernetesSecrets:
      - secretName: ""
        keys:
          TIMESCALEDB_USERNAME: ""
          TIMESCALEDB_PASSWORD: ""
          TIMESCALEDB_SSL_ROOT_CERT: ""
    secretManagement:
      externalSecretsOperator:
        - secretStore:
            name: ""
            kind: ""
          remoteKeys:
            TIMESCALEDB_USERNAME:
              name: ""
              property: ""
            TIMESCALEDB_PASSWORD:
              name: ""
              property: ""
            TIMESCALEDB_SSL_ROOT_CERT:
              name: ""
              property: ""
database:
  mongo:
    ngharness:
      enabled: false
      protocol: ""
      hosts: []
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              MONGO_USER: ""
              MONGO_PASSWORD: ""
        secretManagement:
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                MONGO_USER:
                  name: ""
                  property: ""
                MONGO_PASSWORD:
                  name: ""
                  property: ""
    notifications:
      enabled: false
      protocol: ""
      hosts: []
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              MONGO_USER: ""
              MONGO_PASSWORD: ""
        secretManagement:
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                MONGO_USER:
                  name: ""
                  property: ""
                MONGO_PASSWORD:
                  name: ""
                  property: ""
    pmsharness:
      enabled: false
      protocol: ""
      hosts: []
      extraArgs: ""
      secrets:
        kubernetesSecrets:
          - secretName: ""
            keys:
              MONGO_USER: ""
              MONGO_PASSWORD: ""
        secretManagement:
          externalSecretsOperator:
            - secretStore:
                name: ""
                kind: ""
              remoteKeys:
                MONGO_USER:
                  name: ""
                  property: ""
                MONGO_PASSWORD:
                  name: ""
                  property: ""
replicaCount: 1
maxSurge: 1
maxUnavailable: 0
allowedOrigins: ""
appLogLevel: "INFO"
image:
  registry: us.gcr.io/platform-205701
  repository: ng-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.19.2"
  digest: ""
  imagePullSecrets: []
initContainer:
  image:
    registry: docker.io
    repository: busybox
    tag: "1.35.0"
    digest: ""
    imagePullSecrets: []
mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password
ceSecret:
  access_key:
    name: nextgen-ce
    key: AWS_ACCESS_KEY
  secret_key:
    name: nextgen-ce
    key: AWS_SECRET_KEY
  destination_bucket:
    name: nextgen-ce
    key: AWS_DESTINATION_BUCKET
  template_url:
    name: nextgen-ce
    key: AWS_TEMPLATE_LINK
ceGcpSetupConfigGcpProjectId: "placeHolderGcpProjectId"
timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword
java:
  memory: "4096m"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"
podAnnotations: {}
imagePullSecrets: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext:
  runAsUser: 65534
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
probes:
  readinessProbe:
    httpGet:
      path: /health
      port: http-ng-manager
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 5
  livenessProbe:
    httpGet:
      path: /health
      port: http-ng-manager
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 5
  startupProbe:
    httpGet:
      path: /health
      port: http-ng-manager
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 25
service:
  annotations: {}
  type: ClusterIP
  protocol: TCP
  port: 7090
  grpcport: 9979
  gitsyncgrpcport: 13002
resources:
  limits:
    memory: 8192Mi
  requests:
    cpu: 2
    memory: 200Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPU: ""
  targetMemory: ""
nodeSelector: {}
tolerations: []
affinity: {}
additionalConfigs: {}
java17flags: ""
# extraVolumes:
# - name: volume-test
#   configMap:
#     name: test-config
#     readOnly: true
extraVolumes: []
# extraVolumeMounts:
#   - name: test-volume-mount
#     mountPath: /opt/harness/config
extraVolumeMounts: []
# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#   preStop:
#     exec:
#       command:

# extraEnvVars:
# - name: POD_NAME
#   valueFrom:
#     fieldRef:
#       fieldPath: metadata.name
extraEnvVars: []
virtualService:
  annotations: {}
ingress:
  annotations: {}
secrets:
  default:
    LOG_STREAMING_SERVICE_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
    OPA_SERVER_SECRET: dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq
    GITOPS_SERVICE_SECRET: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=
    CE_AWS_ACCESS_KEY: ""
    CE_AWS_SECRET_KEY: ""
    CE_AWS_DESTINATION_BUCKET: ""
    CE_AWS_TEMPLATE_URL: ""
  kubernetesSecrets:
    - secretName: ""
      keys:
        LOG_STREAMING_SERVICE_TOKEN: ""
        OPA_SERVER_SECRET: ""
        GITOPS_SERVICE_SECRET: ""
        CE_AWS_ACCESS_KEY: ""
        CE_AWS_SECRET_KEY: ""
        CE_AWS_DESTINATION_BUCKET: ""
        CE_AWS_TEMPLATE_URL: ""
  secretManagement:
    externalSecretsOperator:
      - secretStore:
          name: ""
          kind: ""
        remoteKeys:
          LOG_STREAMING_SERVICE_TOKEN:
            name: ""
            property: ""
          OPA_SERVER_SECRET:
            name: ""
            property: ""
          GITOPS_SERVICE_SECRET:
            name: ""
            property: ""
          CE_AWS_ACCESS_KEY:
            name: ""
            property: ""
          CE_AWS_SECRET_KEY:
            name: ""
            property: ""
          CE_AWS_DESTINATION_BUCKET:
            name: ""
            property: ""
          CE_AWS_TEMPLATE_URL:
            name: ""
            property: ""
config:
  GITOPS_SERVICE_CLIENT_BASEURL: http://gitops:7908/api/v1/
  CACHE_BACKEND: REDIS
  DEPLOY_MODE: KUBERNETES_ONPREM
  MANAGER_TARGET: harness-manager:9879
  MANAGER_AUTHORITY: harness-manager:9879
  NG_MANAGER_TARGET: ng-manager:13002
  NG_MANAGER_AUTHORITY: ng-manager:13002
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: harness-redis
  GRPC_SERVER_PORT: "9979"
  SHOULD_CONFIGURE_WITH_PMS: "true"
  PMS_GITSYNC_TARGET: pipeline-service:14002
  PMS_GITSYNC_AUTHORITY: pipeline-service:14002
  TEMPLATE_GITSYNC_TARGET: template-service:16002
  TEMPLATE_GITSYNC_AUTHORITY: template-service:16002
  PMS_TARGET: pipeline-service:12011
  PMS_AUTHORITY: pipeline-service:12011
  LOCK_CONFIG_SENTINEL_MASTER_NAME: harness-redis
  USE_REDIS_FOR_SDK_RESPONSE_EVENTS: "true"
  MOCK_ACCESS_CONTROL_SERVICE: "false"
  ACCESS_CONTROL_ENABLED: "true"
  ENABLE_DEFAULT_RESOURCE_GROUP_CREATION: "true"
  ENABLE_DASHBOARD_TIMESCALE: "true"
  AUDIT_ENABLED: "true"
  SCM_SERVICE_URI: scm-service:8091
  NG_MANAGER_CLIENT_BASEURL: http://ng-manager:7090/
  NG_MANAGER_API_URL: http://ng-manager:7090/
  SERVICE_DISCOVERY_SERVICE_BASE_URL: http://service-discovery-manager:8080/
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: "true"
  MONGO_TRANSACTIONS_ALLOWED: "false"
  NOTIFICATION_BASE_URL: http://platform-service:9005/api/
  TEMPLATE_SERVICE_ENDPOINT: http://template-service:15002/api/
  PIPELINE_SERVICE_CLIENT_BASEURL: http://pipeline-service:12001/api/
  CI_MANAGER_SERVICE_CLIENT_BASEURL: http://ci-manager:7090/
  CVNG_SERVICE_CLIENT_BASEURL: http://cv-nextgen:6060/cv/api/
  IDP_SERVICE_CLIENT_BASE_URL: http://idp-service:12003/
  STO_CORE_SERVICE_CLIENT_BASEURL: http://sto-core:4000/api/
